---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  labels:
    app: test-bridge-k8s-webservice
  name: "test-bridge-k8s-webservice"
spec:
  serviceName: "test-bridge-k8s-webservice"
  replicas: 1
  selector:
    matchLabels:
      app: test-bridge-k8s-webservice
  template:
    metadata:
      labels:
        app: test-bridge-k8s-webservice
        tier: backend
    spec:
      containers:
        - image: "stevekieu/test-bridge-k8s-webservice:20210903-1"
          name: "test-bridge-k8s-webservice"
          ports:
            - containerPort: 8080
              name: http-port
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              #cpu: 20m
